name: AreaProtect
main: AreaProtect\Main
version: 1.0.0
api: [1.1.0]

load: POSTWORLD
authors: [Comedyman937]
description: Protect your worlds from griefers!

permissions:
    areaprotect.action.edit:
        description: "Allows players to edit worlds!"
        default: op
